# Generated by Django 2.1.4 on 2019-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=128)),
                ('user_password', models.CharField(max_length=15)),
                ('user_primary_contact', models.CharField(max_length=15)),
                ('user_secondary_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
