# Generated by Django 2.1.4 on 2019-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_primary_contact',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_secondary_contact',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]